### ISSUE TITLE
README steps are not working on windows

### ISSUE THREAD

**Issue by 0hsn** [chkware/chkware.github.io#20] opened 2022-03-17 10:41 UTC
On my windows machine I tried with as given on README. But it failed with following image.

![image](https://user-images.githubusercontent.com/3197377/158791804-984953c3-f175-4ad4-a058-99e752ce2bfd.png)

Platform windows 10
Node 16.14.1

> I will also try on Linux and update here

**Comment by arifszn** [comment] 2022-03-17 11:32
Couldn't reproduce this error yet. Still checking.

- Fresh clone
- Platform windows 10
- Node v16.13.1

Can you try again deleting the `package-lock.json` file, `node_modules` folder and again running `npm install`?

**Comment by 0hsn** [comment] 2022-03-17 11:53
it builds perfectly now! :tada: 
I found what I did wrong was I accidentally update `docusaurus` version :exploding_head:

**Comment by arifszn** [comment] 2022-03-17 12:08
Should we close this issue then?

**Closed** 2022-03-17 12:14 UTC
Labels: bug
